import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from "next/router"
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import BottomNavigation from '@/components/BottomNavigation'
import LoginForm from '@/components/LoginForm'
import SignInForm from '@/components/SignInForm'
import ChatInterface from '@/components/ChatInterface'
import { useEffect } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className + " static select-none"}>
        <Navbar />
        <div className='h-10'></div>
        <div className='mx-4 md:mx-auto max-w-4xl flex gap-x-4'>
          <div className='w-1/4 bg-teal-400 hidden md:block'>

          </div>

          <div className='w-full md:w-3/4'>
            {/* <LoginForm /> */}
            {/* <ChatInterface /> */}
            <SignInForm />

          </div>
        </div>
        <div className='h-24'></div>
        <BottomNavigation />
      </main>
    </>
  )
}
